### ISSUE TITLE
indexamajig exits with status 0 when it fails to read files

### ISSUE THREAD

**Issue by takluyver** [biochem-fan/CrystFEL#5]
I was trying to run a build of CrystFEL which was compiled against HDF5 1.8, and it was failing to open the virtual datasets. However, the exit code of indexamajig was 0, which conventionally indicates that a program has run successfully.

I'm guessing that this is because the worker processes try and fail to open the files, but the main controller process restarts fails workers and continues trying to process even though they never work. I can see this makes sense in general - we've noticed that processing often times out on a small number of frames, and it's clearly useful to continue working after those. But it seems unfortunate that it can completely fail to process and still exit as if it had succeeded.

Possible ideas:

1. The controller could try to open files & datasets before calling the workers, so it fails fast if that doesn't work. But that might not be practical if you have thousands of files with one image each.
2. Exit with an error code if 0 images are processed
3. Have a configurable threshold to return an error if e.g. < 95% of specified images are successfully processed.

**Comment by biochem-fan** [comment]
Hi, this repository is an unofficial fork of CrystFEL for SACLA. For general feedback, please write to Dr. Thomas White http://www.desy.de/~twhite/crystfel/contact.html.

**Comment by takluyver** [comment]
Aha, thanks, I've emailed him now.
